### ISSUE TITLE
Bug: Iron glass doors won't register as iron doors

### ISSUE THREAD

**Issue by EGOIST1372** [kyrptonaught/Glass-Doors#14]
Iron glass doors won't register as iron doors and not working properly with [presence footsteps](https://www.curseforge.com/minecraft/mc-mods/presence-footsteps) mod
glass iron door
![image](https://user-images.githubusercontent.com/86555131/154707127-3d9a1d90-ed10-4f60-b97b-5aee6ad8346b.png)
normal iron door (says metal clinking in sound subtitles)
![image](https://user-images.githubusercontent.com/86555131/154707298-6b7659bb-a0e6-4b17-9d4d-d60eb2083531.png)

**Comment by EGOIST1372** [comment]
the issue moved to [correct repo](https://github.com/ReviversMC/modern-glass-doors/issues/7)

**Comment by yesn0t** [comment]
may i ask which mods add the coordinates and direction (top left) , and make the subtitles translucent (bottom right) ?
thanks

**Comment by EGOIST1372** [comment]
> 
ASH(another simple hud) is for coordinates
and for that subtitle you just need to go to subtitle setting and set background to everywhere (vanilla setting-no mod required)
