### ISSUE TITLE
Mangrove & Bamboo Glass Doors for 1.19.3?

### ISSUE THREAD

**Issue by Kitteh6660** [kyrptonaught/Glass-Doors#16]
Seeing as the mod still doesn't have them, I thought I would whip up some idea for new glass doors!

It would be nice bringing the mod in line with the vanilla doors. I've even whipped up some textures for mangrove and bamboo glass doors!

![MangroveBambooGlassDoors](https://user-images.githubusercontent.com/5838739/206935505-0eed1084-fe11-42f9-9a19-d6a809b31f74.png)

I've created a ZIP file for bamboo and mangrove glass door and trapdoor textures.
[MangroveBambooGlassDoorTextures.zip](https://github.com/kyrptonaught/Glass-Doors/files/10203551/MangroveBambooGlassDoorTextures.zip)

**Comment by thefirethirteen** [comment]
Awesome, thanks for contributing! I'll most definitely use them soon!

**Comment by kyrptonaught** [comment]
Looks great! Thanks for the contribution!

**Comment by Kitteh6660** [comment]
Glad to hear that! Looking forward for the additions!

**Comment by thefirethirteen** [comment]
Will be in the new release (actually) coming very soon!

**Comment by thefirethirteen** [comment]
New release is up!

**Comment by Kitteh6660** [comment]
Awesome! 

BTW, I will also create the cherry glass door textures for 1.19.4. :)

Edit: Here you go!
[CherryGlassDoorTextures.zip](https://github.com/kyrptonaught/Glass-Doors/files/10809788/CherryGlassDoorTextures.zip)
